env:
  BUILDKITE_PLUGIN_DOCKER_COMPOSE_CONFIG: step-types-example/docker-compose.yml

steps:
  - label: ":docker::package:"
    plugins:
      - docker-compose#v3.3.0:
          build: app
          image-repository: "index.docker.io/buildkitedemo/step-types-demo"
  - wait
  - label: ":rubocop:"
    command: "echo hello world"
    plugins:
      - docker-compose#v3.3.0:
          run: app
  - label: ":percy:"
    command: "echo hello world"
    plugins:
      - docker-compose#v3.3.0:
          run: app
  - label: ":knapsack:"
    command: "echo hello world"
    parallelism: 30
    plugins:
      - docker-compose#v3.3.0:
          run: app
  - wait
  - label: ":codecov:"
    command: "echo coverage"
  - wait
  - trigger: "naming-things-is-hard-deploys"
    label: ":shipit:"
    branches: "master"
    build:
      commit: "$BUILDKITE_COMMIT"
      branch: "master"