steps:
  - label: ":docker: :package: (Dev)"
    plugins:
      - docker-login#v2.1.0:
          username: buildkitedemo
      - docker-compose#v4.14.0:
          build: app
          image-repository: "buildkitedemo/docker-demo"

  - wait

  - label: ":node: Units"
    command: "npm test"
    plugins:
      - docker-login#v2.1.0:
          username: buildkitedemo
      - docker-compose#v4.14.0:
          run: app

  - label: ":node: Lint"
    command: "npm run lint"
    plugins:
      - docker-login#v2.1.0:
          username: buildkitedemo
      - docker-compose#v4.14.0:
          run: app

  - wait

  - label: ":chrome: Integration"
    plugins:
      - docker-login#v2.1.0:
          username: buildkitedemo
      - docker-compose#v4.14.0:
          config: integration-tests/docker-compose.yml
          run: integration-tests

  - wait

  - label: ":docker: :package: (Prod)"
    plugins:
      - docker-login#v2.1.0:
          username: buildkitedemo
      - docker-compose#v4.14.0:
          config: docker-compose.prod.yml
          push: app

  - wait

  - label: ":chrome: Integration (Prod)"
    plugins:
      - docker-login#v2.1.0:
          username: buildkitedemo
      - docker-compose#v4.14.0:
          config: integration-tests/docker-compose.prod.yml
          run: integration-tests

  - wait

  - label: ":rocket:"
    branches:
      - master
      - add-deploy-to-docker-pipeline
    trigger: "${BUILDKITE_PIPELINE_SLUG}-deploy"
    build:
      commit: "${BUILDKITE_COMMIT}"
      branch: master
      message: ":rocket:"
      env:
        BUILD_NUMBER_TO_DEPLOY: "$BUILDKITE_BUILD_NUMBER}"
    async: true